services:
  afterimage-db:
    container_name: afterimage-db-redis
    image: "redis:8.0.0"
    hostname: redis
    ports:
      - "6380:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
  afterimage-app:
    container_name: afterimage-app-redis
    image: avlo/afterimage-nostr-reputation-relay:1.0.0
    ports:
      - "5556:5556"
    links:
      - afterimage-db
    environment:
      SPRING_PROFILES_ACTIVE: prod_ws
volumes:
  afterimage-db:
    driver: local
