services:
  afterimage-db:
    container_name: afterimage-db-redis-local_ws
    image: "redis:8.0.0"
    hostname: localhost
    ports:
      - "6380:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
    networks:
      - docker_network
volumes:
  afterimage-db:
    driver: local
networks:
  docker_network:
    driver: bridge
