services:
  afterimage-db:
    container_name: afterimage-db-redis-local-gradle
    image: "redis:8.0.0"
    hostname: localhost
    ports:
      - "6380:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
volumes:
  afterimage-db:
    driver: local
