services:
  afterimage-db:
    container_name: afterimage-db-redis-dev_ws
    image: "redis:8.0.0"
    hostname: redis
    ports:
      - "6380:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
  afterimage-app:
    container_name: afterimage-app-redis-dev_ws
    image: afterimage-app-redis:0.2.2
    ports:
      - "5556:5556"
    links:
      - afterimage-db
    environment:
      SPRING_PROFILES_ACTIVE: dev_ws
volumes:
  afterimage-db:
    driver: local
